version: 2
enable-beta-ecosystems: true
updates:
  - package-ecosystem: "docker-compose"
    directory: "/"
    schedule:
      interval: "weekly" # Can be "daily", "weekly", "monthly"
    allow:
      - dependency-type: "direct"
    target-branch: "main"
    commit-message:
      prefix: "docker"
      include: "scope"
