global:
  scrape_interval: 10s
  # external_labels:
  #   cluster: 'vm-cluster'
  #   namespace: 'monitoring'

scrape_configs:
  # ===========================================
  # System Exporters (Node & Container Metrics)
  # ===========================================
  - job_name: node-exporter
    static_configs:
      - targets:
          - node-exporter:9100
        labels:
          container: 'node-exporter'

  - job_name: cadvisor
    static_configs:
      - targets:
          - cadvisor:8080
        labels:
          container: 'cadvisor'

    # relabel_configs:
    #   - source_labels: [container_label_com_docker_extension_.*]
    #     action: labeldrop
  # ===========================================
  # Alerting & Monitoring
  # ===========================================
  - job_name: alertmanager
    static_configs:
      - targets:
          - alertmanager:9093
        labels:
          container: 'alertmanager'

  - job_name: vmalert
    static_configs:
      - targets:
          - vmalert:8880
        labels:
          component: 'vmalert'

  # ===========================================
  # VictoriaMetrics Cluster Components
  # ===========================================
  - job_name: vmagent
    static_configs:
      - targets:
          - vmagent:8429
        labels:
          component: 'vmagent'

  - job_name: vmauth
    static_configs:
      - targets:
          - vmauth:8427
        labels:
          component: 'vmauth'

  - job_name: vminsert
    static_configs:
      - targets:
          - vminsert-1:8480
          - vminsert-2:8480
        labels:
          component: 'vminsert'

  - job_name: vmselect
    static_configs:
      - targets:
          - vmselect-1:8481
          - vmselect-2:8481
        labels:
          component: 'vmselect'

  - job_name: vmstorage
    static_configs:
      - targets:
          - vmstorage-1:8482
          - vmstorage-2:8482
        labels:
          component: 'vmstorage'

# ===========================================
# VictoriaLogs
# ===========================================
  - job_name: vlstorage
    static_configs:
    - targets:
      - vlstorage-1:9491
      - vlstorage-2:9491
  - job_name: vlselect
    static_configs:
    - targets:
      - vlselect-1:9471
      - vlselect-2:9471
  - job_name: vlinsert
    static_configs:
    - targets:
      - vlinsert:9481