api:
  enabled: true
  address: 0.0.0.0:8686

sources:
  docker:
    type: docker_logs
  
  vector_metrics:
    type: internal_metrics

transforms:
  # Parse Docker labels and add Kubernetes-like labels
  docker_labels:
    type: remap
    inputs: [docker]
    source: |
      # Extract Docker Compose labels
      .container_name = .container.name
      .namespace = .label.stackname
      .app = .label."com.docker.compose.service"
      .pod_name = .container.name
      
      # Add host info
      .host = "docker-host"
      
      # Parse timestamp if available
      .timestamp = parse_timestamp(.timestamp, format: "%+") ?? now()

  msg_parser:
    type: remap
    inputs: [docker_labels]  # Changed from [docker]
    source: |
      .message = parse_json(.message) ?? .message

sinks:
  # VictoriaLogs Cluster - Direct to vlinsert (no auth needed)
  victorialogs:
    type: elasticsearch
    inputs: [msg_parser]
    endpoints: ["http://vlinsert:9481/insert/elasticsearch/"]
    mode: bulk
    api_version: v8
    compression: gzip
    healthcheck:
      enabled: false
    request:
      headers:
        # VL-Stream-Fields: container_name,namespace,app,host,pod_name
        VL-Stream-Fields: container_name,namespace,app,host,pod_name,logging_jobname,stackname
        VL-Time-Field: timestamp
        VL-Msg-Field: message,log
        AccountID: "0"
        ProjectID: "0"
  
  # VictoriaMetrics Cluster - via vmauth with auth
  victoriametrics:
    type: prometheus_remote_write
    endpoint: http://vmauth:8427/insert/0/prometheus/api/v1/write
    inputs: [vector_metrics]
    healthcheck:
      enabled: false
    auth:
      strategy: basic
      user: admin
      password: changeme