{
 "title": "Vector Cluster Monitoring",
 "description": "Vector.dev Kubernetes cluster monitoring dashboard",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "ds", "label": "Datasource", "query": "prometheus" },
   {
    "name": "pod",
    "query": {
     "query": "label_values(kube_pod_info{pod=~\"vector-agent-.*\"},pod)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Vector utilization",
   "type": "timeseries",
   "description": "A ratio from 0 to 1 of the load on a component. A value of 0 would indicate a completely idle component that is simply waiting for input. A value of 1 would indicate a that is never idle. This value is updated every 5 seconds.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "avg by (component_type) (vector_utilization)",
     "legendFormat": "{{component_id}}"
    }
   ]
  },
  {
   "title": "Vector utilization",
   "type": "piechart",
   "description": "A ratio from 0 to 1 of the load on a component. A value of 0 would indicate a completely idle component that is simply waiting for input. A value of 1 would indicate a that is never idle. This value is updated every 5 seconds.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg by (component_type) (vector_utilization)",
     "legendFormat": "{{component_id}}"
    }
   ]
  },
  {
   "title": "Events count (events/sec)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "targets": [
    {
     "expr": "sum by (component_kind) (rate(vector_component_received_events_total{component_kind=\"source\", host=~\"$pod\"}[1m]))",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by (component_kind) (rate(vector_component_received_events_total{component_kind=\"transform\", host=~\"$pod\"}[1m]))",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by (component_kind) (rate(vector_component_received_events_total{component_kind=\"sink\", host=~\"$pod\"}[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Events count (events/sec)",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (component_kind) (rate(vector_component_received_events_total{component_kind=\"source\", host=~\"$pod\"}[1m]))",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by (component_kind) (rate(vector_component_received_events_total{component_kind=\"transform\", host=~\"$pod\"}[1m]))",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by (component_kind) (rate(vector_component_received_events_total{component_kind=\"sink\", host=~\"$pod\"}[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Events size(bytes/sec)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "sum by (component_kind) (rate(vector_component_received_event_bytes_total{component_kind=\"source\", host=~\"$pod\"}[1m]))",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by (component_kind) (rate(vector_component_received_event_bytes_total{component_kind=\"transform\", host=~\"$pod\"}[1m]))",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by (component_kind) (rate(vector_component_received_event_bytes_total{component_kind=\"sink\", host=~\"$pod\"}[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Events size(bytes/sec)",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (component_kind) (rate(vector_component_received_event_bytes_total{component_kind=\"source\", host=~\"$pod\"}[1m]))",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by (component_kind) (rate(vector_component_received_event_bytes_total{component_kind=\"transform\", host=~\"$pod\"}[1m]))",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by (component_kind) (rate(vector_component_received_event_bytes_total{component_kind=\"sink\", host=~\"$pod\"}[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Buffer size",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by(host) (vector_buffer_byte_size{buffer_type=\"memory\", host=~\"$pod\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Buffer size",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(host) (vector_buffer_byte_size{buffer_type=\"memory\", host=~\"$pod\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "INPUT",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 },
   "collapsed": true,
   "panels": [
    {
     "title": "Input events count (events/sec)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 34 },
     "fieldConfig": { "defaults": { "unit": "cps" } },
     "targets": [
      {
       "expr": "sum by (component_id) (rate(vector_component_received_events_total{component_kind=\"source\", host=~\"$pod\"}[1m]))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Input bytes rate (bytes/sec)",
     "type": "timeseries",
     "description": "The rate of bytes processed by the component.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 34 },
     "fieldConfig": { "defaults": { "unit": "binBps" } },
     "targets": [
      {
       "expr": "sum by (component_id) (rate(vector_component_received_event_bytes_total{component_kind=\"source\", host=~\"$pod\"}[1m]))",
       "legendFormat": "{{ component_id }}"
      }
     ]
    },
    {
     "title": "Input events count per host (events/sec)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 42 },
     "fieldConfig": { "defaults": { "unit": "cps" } },
     "targets": [
      {
       "expr": "sum by (host) (rate(vector_component_received_events_total{component_kind=\"source\", host=~\"$pod\"}[1m]))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Input bytes rate per host (bytes/sec)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 42 },
     "fieldConfig": { "defaults": { "unit": "binBps" } },
     "targets": [
      {
       "expr": "sum by (host) (rate(vector_component_received_bytes_total{component_kind=\"source\", host=~\"$pod\"}[1m]))",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "TRANSFORM",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 },
   "collapsed": true,
   "panels": [
    {
     "title": "Transform events count (events/sec)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 51 },
     "fieldConfig": { "defaults": { "unit": "cps" } },
     "targets": [
      {
       "expr": "sum by (component_id) (rate(vector_component_received_events_total{component_kind=\"transform\", host=~\"$pod\"}[1m]))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Transform bytes rate (bytes/sec)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 51 },
     "fieldConfig": { "defaults": { "unit": "binBps" } },
     "targets": [
      {
       "expr": "sum by (component_id) (rate(vector_component_received_event_bytes_total{component_kind=\"transform\", host=~\"$pod\"}[1m]))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Transform events count per host (events/sec)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 59 },
     "fieldConfig": { "defaults": { "unit": "cps" } },
     "targets": [
      {
       "expr": "sum by (host) (rate(vector_component_received_events_total{component_kind=\"transform\", host=~\"$pod\"}[1m]))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Transform bytes rate per host (bytes/sec)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 59 },
     "fieldConfig": { "defaults": { "unit": "binBps" } },
     "targets": [
      {
       "expr": "sum by (host) (rate(vector_component_received_event_bytes_total{component_kind=\"transform\", host=~\"$pod\"}[1m]))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Transform utilization",
     "type": "timeseries",
     "description": "A ratio from 0 to 1 of the load on a component. A value of 0 would indicate a completely idle component that is simply waiting for input. A value of 1 would indicate a that is never idle. This value is updated every 5 seconds.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 67 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "avg by (component_id) (vector_utilization{component_kind=\"transform\"})",
       "legendFormat": "{{component_id}}"
      }
     ]
    },
    {
     "title": "Transform utilization",
     "type": "piechart",
     "description": "A ratio from 0 to 1 of the load on a component. A value of 0 would indicate a completely idle component that is simply waiting for input. A value of 1 would indicate a that is never idle. This value is updated every 5 seconds.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 67 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "avg by (component_id) (vector_utilization{component_kind=\"transform\"})",
       "legendFormat": "{{component_id}}"
      }
     ]
    }
   ]
  },
  {
   "title": "OUTPUT",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 35 },
   "collapsed": true,
   "panels": [
    {
     "title": "Output events count (events/sec)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 52 },
     "fieldConfig": { "defaults": { "unit": "cps" } },
     "targets": [
      {
       "expr": "sum by (component_id) (rate(vector_component_received_events_total{component_kind=\"sink\", host=~\"$pod\"}[1m]))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Output events bytes (bytes/sec)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 52 },
     "fieldConfig": { "defaults": { "unit": "binBps" } },
     "targets": [
      {
       "expr": "sum by (component_id) (rate(vector_component_received_event_bytes_total{component_kind=\"sink\", host=~\"$pod\"}[1m]))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Output events count per host (events/sec)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 60 },
     "fieldConfig": { "defaults": { "unit": "cps" } },
     "targets": [
      {
       "expr": "sum by (host) (rate(vector_component_received_events_total{component_kind=\"sink\", host=~\"$pod\"}[1m]))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Output events size per host (bytes/sec)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 60 },
     "fieldConfig": { "defaults": { "unit": "binBps" } },
     "targets": [
      {
       "expr": "sum by (host) (rate(vector_component_received_event_bytes_total{component_kind=\"sink\", host=~\"$pod\"}[1m]))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Output utilization",
     "type": "timeseries",
     "description": "A ratio from 0 to 1 of the load on a component. A value of 0 would indicate a completely idle component that is simply waiting for input. A value of 1 would indicate a that is never idle. This value is updated every 5 seconds.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 68 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "avg by (component_id) (vector_utilization{component_kind=\"sink\"})",
       "legendFormat": "{{component_id}}"
      }
     ]
    },
    {
     "title": "Output utilization",
     "type": "piechart",
     "description": "A ratio from 0 to 1 of the load on a component. A value of 0 would indicate a completely idle component that is simply waiting for input. A value of 1 would indicate a that is never idle. This value is updated every 5 seconds.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 68 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "avg by (component_id) (vector_utilization{component_kind=\"sink\"})",
       "legendFormat": "{{component_id}}"
      }
     ]
    }
   ]
  },
  {
   "title": "BUFFER",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 36 },
   "collapsed": true,
   "panels": [
    {
     "title": "Buffer size",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 53 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum by(component_id) (vector_buffer_byte_size{buffer_type=\"memory\", host=~\"$pod\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Buffer size per host",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 53 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum by(host) (vector_buffer_byte_size{buffer_type=\"memory\", host=~\"$pod\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Buffer sent size (bytes/sec)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 61 },
     "fieldConfig": { "defaults": { "unit": "binBps" } },
     "targets": [
      {
       "expr": "sum by(component_id) (rate(vector_buffer_sent_bytes_total{buffer_type=\"memory\", host=~\"$pod\"}[1m]))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Buffer sent size per host (bytes/sec)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 61 },
     "fieldConfig": { "defaults": { "unit": "binBps" } },
     "targets": [
      {
       "expr": "sum by(host) (rate(vector_buffer_sent_bytes_total{buffer_type=\"memory\", host=~\"$pod\"}[1m]))",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Buffer sent events (count/sec)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 69 },
     "fieldConfig": { "defaults": { "unit": "cps" } },
     "targets": [
      {
       "expr": "sum by(component_id) (rate(vector_buffer_sent_events_total{buffer_type=\"memory\", host=~\"$pod\"}[1m]))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Buffer sent events per host (count/sec)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 69 },
     "fieldConfig": { "defaults": { "unit": "cps" } },
     "targets": [
      {
       "expr": "sum by(host) (rate(vector_buffer_sent_events_total{buffer_type=\"memory\", host=~\"$pod\"}[1m]))",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Buffer received size (bytes/sec)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 77 },
     "fieldConfig": { "defaults": { "unit": "binBps" } },
     "targets": [
      {
       "expr": "sum by(component_id) (rate(vector_buffer_received_bytes_total{buffer_type=\"memory\", host=~\"$pod\"}[1m]))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Buffer received size per host (bytes/sec)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 77 },
     "fieldConfig": { "defaults": { "unit": "binBps" } },
     "targets": [
      {
       "expr": "sum by(host) (rate(vector_buffer_received_bytes_total{buffer_type=\"memory\", host=~\"$pod\"}[1m]))",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Buffer received events (count/sec)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 85 },
     "fieldConfig": { "defaults": { "unit": "cps" } },
     "targets": [
      {
       "expr": "sum by(component_id) (rate(vector_buffer_received_events_total{buffer_type=\"memory\", host=~\"$pod\"}[1m]))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Buffer received events per host (count/sec)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 85 },
     "fieldConfig": { "defaults": { "unit": "cps" } },
     "targets": [
      {
       "expr": "sum by(host) (rate(vector_buffer_received_events_total{buffer_type=\"memory\", host=~\"$pod\"}[1m]))",
       "legendFormat": "{{pod}}"
      }
     ]
    }
   ]
  }
 ]
}