groups:
- name: node-exporter
  interval: 30s
  rules:
  - alert: NodeOutOfMemory
    annotations:
      summary: Node out of memory (instance {{ $labels.instance }})
      description: "Node memory is filling up (< 10% left)\n  VALUE = {{ $value }}\n  LABELS = {{ $labels }}"
    labels:
      severity: warning
    expr: (node_memory_MemAvailable_bytes / node_memory_MemTotal_bytes * 100 < 10) * on(instance) group_left (nodename) node_uname_info{nodename=~".+"}
    for: 2m

  - alert: NodeMemoryUnderMemoryPressure
    annotations:
      summary: Node memory under memory pressure (instance {{ $labels.instance }})
      description: "The node is under heavy memory pressure. High rate of major page faults\n  VALUE = {{ $value }}\n  LABELS = {{ $labels }}"
    labels:
      severity: warning
    expr: (rate(node_vmstat_pgmajfault[1m]) > 1000) * on(instance) group_left (nodename) node_uname_info{nodename=~".+"}
    for: 2m

  - alert: NodeFilesystemAlmostOutOfSpace
    annotations:
      description: "Filesystem on {{ $labels.device }} at {{ $labels.instance }} has only {{ printf \"%.2f\" $value }}% available space left."
      summary: "Filesystem has less than 5% space left."
    expr: |
      (
        node_filesystem_avail_bytes{job="node",fstype!=""} / node_filesystem_size_bytes{job="node",fstype!=""} * 100 < 5
      and
        node_filesystem_readonly{job="node",fstype!=""} == 0
      )
    for: 1h
    labels:
      severity: warning

  - alert: NodeFilesystemAlmostOutOfSpace
    annotations:
      description: "Filesystem on {{ $labels.device }} at {{ $labels.instance }} has only {{ printf \"%.2f\" $value }}% available space left."
      summary: "Filesystem has less than 3% space left."
    expr: |
      (
        node_filesystem_avail_bytes{job="node",fstype!=""} / node_filesystem_size_bytes{job="node",fstype!=""} * 100 < 3
      and
        node_filesystem_readonly{job="node",fstype!=""} == 0
      )
    for: 1h
    labels:
      severity: critical

  - alert: NodeNetworkReceiveErrs
    annotations:
      description: "{{ $labels.instance }} interface {{ $labels.device }} has encountered {{ printf \"%.0f\" $value }} receive errors in the last two minutes."
      summary: "Network interface is reporting many receive errors."
    expr: |
      rate(node_network_receive_errs_total[2m]) / rate(node_network_receive_packets_total[2m]) > 0.01
    for: 1h
    labels:
      severity: warning

  - alert: NodeNetworkTransmitErrs
    annotations:
      description: "{{ $labels.instance }} interface {{ $labels.device }} has encountered {{ printf \"%.0f\" $value }} transmit errors in the last two minutes."
      summary: "Network interface is reporting many transmit errors."
    expr: |
      rate(node_network_transmit_errs_total[2m]) / rate(node_network_transmit_packets_total[2m]) > 0.01
    for: 1h
    labels:
      severity: warning

- name: cadvisor
  interval: 30s
  rules:
  - alert: ContainerMemoryUsageHigh
    annotations:
      summary: "Container {{ $labels.name }} memory usage is high"
      description: "The container {{ $labels.name }} on instance {{ $labels.instance }} is using more than 80% of its allocated memory.\nVALUE = {{ $value }}\nLABELS = {{ $labels }}"
    expr: (container_memory_usage_bytes{name=~".+", container_label_com_docker_compose_project=~"docker-monitoring-stack.*"} / container_spec_memory_limit_bytes) > 0.8
    for: 5m
    labels:
      severity: warning

  - alert: ContainerMemoryAlmostOut
    annotations:
      summary: "Container {{ $labels.name }} memory almost full"
      description: "The container {{ $labels.name }} on instance {{ $labels.instance }} is using more than 90% of its allocated memory.\nVALUE = {{ $value }}\nLABELS = {{ $labels }}"
    expr: (container_memory_usage_bytes{name=~".+", container_label_com_docker_compose_project=~"docker-monitoring-stack.*"} / container_spec_memory_limit_bytes) > 0.9
    for: 2m
    labels:
      severity: critical

  - alert: ContainerCPUUsageHigh
    annotations:
      summary: "Container {{ $labels.name }} CPU usage is high"
      description: "The container {{ $labels.name }} on instance {{ $labels.instance }} is using more than 80% of its allocated CPU.\nVALUE = {{ $value }}\nLABELS = {{ $labels }}"
    expr: rate(container_cpu_usage_seconds_total[1m]) > (container_spec_cpu_quota / container_spec_cpu_period * 0.8)
    for: 5m
    labels:
      severity: warning

  - alert: ContainerRestarts
    expr: changes(container_start_time_seconds[5m]) > 3
    for: 5m
    labels:
      severity: critical
    annotations:
      summary: "Container restart detected: {{ $labels.name }}"
      description: "The container {{ $labels.name }} on instance {{ $labels.instance }} has restarted in the last 5 minutes.\nVALUE = {{ $value }}\nLABELS = {{ $labels }}"
