groups:
- name: vmalert
  interval: 30s
  rules:
  - alert: VMAlertDown
    annotations:
      summary: "VMAlert is down"
      description: "VMAlert instance {{ $labels.instance }} is down for more than 2 minutes.\nVALUE = {{ $value }}\nLABELS = {{ $labels }}"
    expr: up{job="vmalert"} == 0
    for: 2m
    labels:
      severity: critical
      component: vmalert

  - alert: VMAlertExecutionErrors
    annotations:
      summary: "VMAlert has execution errors"
      description: "VMAlert instance {{ $labels.instance }} is experiencing rule execution errors.\nVALUE = {{ $value }}\nLABELS = {{ $labels }}"
    expr: rate(vmalert_execution_errors_total[5m]) > 0
    for: 5m
    labels:
      severity: warning
      component: vmalert

  - alert: VMAlertRemoteWriteErrors
    annotations:
      summary: "VMAlert has remote write errors"
      description: "VMAlert instance {{ $labels.instance }} is experiencing remote write errors.\nVALUE = {{ $value }}\nLABELS = {{ $labels }}"
    expr: rate(vmalert_remotewrite_errors_total[5m]) > 0
    for: 5m
    labels:
      severity: warning
      component: vmalert

  - alert: VMAlertNotifierErrors
    annotations:
      summary: "VMAlert has notifier errors"
      description: "VMAlert instance {{ $labels.instance }} failed to send alerts to Alertmanager.\nVALUE = {{ $value }}\nLABELS = {{ $labels }}"
    expr: rate(vmalert_alerts_send_errors_total[5m]) > 0
    for: 5m
    labels:
      severity: critical
      component: vmalert

  - alert: VMAlertDataSourceUnavailable
    annotations:
      summary: "VMAlert datasource is unavailable"
      description: "VMAlert instance {{ $labels.instance }} cannot reach datasource {{ $labels.addr }}.\nVALUE = {{ $value }}\nLABELS = {{ $labels }}"
    expr: vmalert_datasource_dial_errors_total > 0
    for: 5m
    labels:
      severity: critical
      component: vmalert

  - alert: VMAlertHighMemoryUsage
    annotations:
      summary: "VMAlert high memory usage"
      description: "VMAlert instance {{ $labels.instance }} is using more than 90% of available memory.\nVALUE = {{ $value }}\nLABELS = {{ $labels }}"
    expr: go_memstats_alloc_bytes{job="vmalert"} > 100000000
    for: 5m
    labels:
      severity: warning
      component: vmalert

  - alert: VMAlertConfigReloadFailed
    annotations:
      summary: "VMAlert configuration reload failed"
      description: "VMAlert instance {{ $labels.instance }} failed to reload configuration.\nVALUE = {{ $value }}\nLABELS = {{ $labels }}"
    expr: vmalert_config_last_reload_successful{job="vmalert"} == 0
    for: 2m
    labels:
      severity: warning
      component: vmalert

  - alert: VMAlertTooManyMissedIterations
    annotations:
      summary: "VMAlert is missing too many rule evaluation iterations"
      description: "VMAlert instance {{ $labels.instance }} has missed {{ $value }} rule evaluation iterations. Rules might be slow or VMAlert is overloaded.\nVALUE = {{ $value }}\nLABELS = {{ $labels }}"
    expr: increase(vmalert_iteration_missed_total[5m]) > 0
    for: 10m
    labels:
      severity: warning
      component: vmalert
